<?php
/**
 * All rights reserved.
 * See COPYING.txt for license details.
 */
declare(strict_types=1);
/**
 * @var $block \GingerPay\Payment\Block\Info\Banktransfer
 */
?>
<dl class="payment-method banktransfer">
    <dt class="title"><?= $block->escapeHtml($block->getMethod()->getTitle()) ?></dt>
    <?php if ($block->getMailingAddress()): ?>
        <dd class="content">
            <address class="banktransfer mailing address">
                <?= /* @noEscape */ nl2br($block->escapeHtml($block->getMailingAddress())) ?>
            </address>
        </dd>
    <?php endif; ?>
</dl>
