<?php
declare(strict_types=1);
/**
 * Copyright © Magmodules.eu. All rights reserved.
 * See COPYING.txt for license details.
 *
 * @var $block EMSPay\Payment\Block\Adminhtml\Render\Header
 */
?>
<div class="mm-block-ems">
    <a class="helpbutton" target="_blank"></a>
    <p>
        <strong><?= $block->escapeHtml(__('Developed by Magmodules.')) ?></strong>
        <?= $block->escapeHtml(__('A Magento only eCommerce Agency located in the Netherlands.')) ?>
    </p>
    <table>
        <tbody>
            <tr>
                <td>
                    <div class="icon1"></div>
                    <?= $block->escapeHtml(__('Visit Magmodules.eu')) ?>
                </td>
            </tr>
        </tbody>
    </table>
</div>
