<?php
/**
 * All rights reserved.
 * See COPYING.txt for license details.
 */
declare(strict_types=1);

/**
 * @var $block \GingerPay\Payment\Block\Info\Banktransfer
 */
?>
<?= $block->escapeHtml($block->getMethod()->getTitle()) ?>
<?php if ($block->getInfo()->getAdditionalInformation()): ?>
    <?php if ($block->getMailingAddress()): ?>
        <div class="ing-mailing-address">
            <?= /* @noEscape */ nl2br($block->escapeHtml($block->getMailingAddress())) ?>
        </div>
    <?php endif; ?>
<?php endif; ?>
