<?php
/**
 * All rights reserved.
 * See COPYING.txt for license details.
 */
declare(strict_types=1);

/**
 * @var $block \GingerPay\Payment\Block\Info\KlarnaPayLater
 */
?>
<?= $block->escapeHtml($block->getMethod()->getTitle()) ?>
<?php if ($block->getInfo()->getAdditionalInformation()): ?>
    <?php if ($block->getTestModus()): ?>
        <div class="ing-mailing-address test-key">
            <?= /* @noEscape */ $block->escapeHtml(__('Processed using Test API-Key!')) ?>
        </div>
    <?php endif; ?>
<?php endif; ?>
