<?php
/**
 * All rights reserved.
 * See COPYING.txt for license details.
 */
declare(strict_types=1);

/**
 * @var $block \GingerPay\Payment\Block\Info\Banktransfer
 */
?>
<?= $block->escapeHtml($block->getMethod()->getTitle()) ?>
    {{pdf_row_separator}}
<?php if ($block->getInfo()->getAdditionalInformation()): ?>
    {{pdf_row_separator}}
    <?php if ($block->getMailingAddress()): ?>
        {{pdf_row_separator}}
        <?= /* @noEscape */ nl2br($block->escapeHtml($block->getMailingAddress())) ?>
        {{pdf_row_separator}}
    <?php endif; ?>
<?php endif; ?>
